%YAML:1.0
cameras:
  - T_SC: [0.9184477012197224, 0.006814501455941813, -0.3954837325277928, -0.08323388702651224,
      0.1357078093951938, 0.9337332184585131, 0.3312486486255676, -0.002218366214987864,
      0.3715335928194994, -0.35790479085507354, 0.8566603469810079, 0.005626638959664241,
      0.0, 0.0, 0.0, 1.0]
    camera_type: gray
    distortion_coefficients: [0.4896735773708656, 0.15364417808237318, -0.00023052089722471787,
      0.0003100581060316594, 0.00907202623907521, 0.760924032106806, 0.1699934621377647,
      0.040322943929294]
    distortion_type: radialtangential8
    focal_length: [269.3157388466649, 269.2500852335917]
    image_dimension: [640, 480]
    principal_point: [323.6367354444056, 245.37262901935367]
    slam_use: okvis
  - T_SC: [0.9169473808337745, 0.004955465029392203, 0.3989773729779966, 0.022239747333591468,
      -0.15123925026697327, 0.929626218566189, 0.3360383652695211, -0.002331785076783077,
      -0.36923460016737975, -0.36847053765622934, 0.8531677870844424, 0.005312605812652759,
      0.0, 0.0, 0.0, 1.0]
    camera_type: gray
    distortion_coefficients: [0.5124456275983791, 0.1183716939017548, 6.664706390223596e-05,
      0.0008408430780571384, 0.011001285241218404, 0.7946602801800285, 0.1281440933685308,
      0.039739477209162065]
    distortion_type: radialtangential8
    focal_length: [270.6592897084914, 270.6889084240239]
    image_dimension: [640, 480]
    principal_point: [323.6443046844411, 250.56110650729707]
    slam_use: okvis

# additional camera parameters
camera_parameters:
    timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance
    sync_cameras: [0, 1] # the cameras that will be synchronised
    image_delay: 0.00 # [s] timestamp_camera_correct = timestamp_camera - image_delay
    online_calibration: # some parameters to set the online
        do_extrinsics: false # Do we online-calibrate extrinsics?
        do_extrinsics_final_ba: false # Do we calibrate extrinsics in final BA?
        sigma_r: 0.01 # T_SCi position prior stdev [m]
        sigma_alpha: 0.05 # T_SCi orientation prior stdev [rad]

imu_parameters:
    use: true
    a_max: 176.0 # acceleration saturation [m/s^2]
    g_max: 7.8 # gyro saturation [rad/s]
    sigma_g_c: 20.0e-4 # gyro noise density [rad/s/sqrt(Hz)]
    sigma_a_c: 20.0e-3 # accelerometer noise density [m/s^2/sqrt(Hz)]
    sigma_bg: 0.01 # gyro bias prior [rad/s]
    sigma_ba: 0.1 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 20.0e-5 # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_aw_c: 20.0e-3 # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    g0: [ 0.0, 0.0, 0.0 ] # initial gyro bias [rad/s]
    a0: [ -0.05, 0.09, 0.01 ] # initial accelerometer bias [m/s^2]
    s_a: [1.0, 1.0, 1.0]
    # transform Body-Sensor (IMU)
    T_BS:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]

# frontend: detection etc.
frontend_parameters:
    detection_threshold: 35.0 #42.0 # detection threshold. By default the uniformity radius in pixels
    absolute_threshold: 3000.0 # absolute Harris corner threshold (noise floor)
    matching_threshold: 60.0 # BRISK descriptor matching threshold
    octaves: 0 # number of octaves for detection. 0 means single-scale at highest resolution
    max_num_keypoints: 700 # restrict to a maximum of this many keypoints per image (strongest ones)
    keyframe_overlap: 0.60 # minimum field-of-view overlap
    use_cnn: false # use the CNN (if available) to filter out dynamic content / sky
    parallelise_detection: true # Run parallel detect & describe.
    num_matching_threads: 4 # Parallelise matching with this number of threads.

# estimator parameters
estimator_parameters:
    num_keyframes: 5 # number of keyframes in optimisation window
    num_loop_closure_frames: 3 # number of loop closure frames in optimisation window
    num_imu_frames: 3 # number of frames linked by most recent nonlinear IMU error terms
    do_loop_closures: true # whether to do VI-SLAM or VIO
    do_final_ba: true # Whether to run a full final BA
    enforce_realtime: false # whether to limit the time budget for optimisation
    realtime_min_iterations: 3 # minimum number of iterations always performed
    realtime_max_iterations: 10 # never do more than these, even if not converged
    realtime_time_limit: 0.035 # time budget for realtime optimisation [s]
    realtime_num_threads: 3 # number of threads for the realtime optimisation
    full_graph_iterations: 15 # don't do more than these for the full (background) optimisation
    full_graph_num_threads: 3 # number of threads for the full (background) optimisation

# some options for how and what to output
output_parameters:
    display_matches: false  # displays debug video and matches. May be slow.
    display_overhead: false # debug overhead image. Is slow.
    display_topview: true
